services:
  - type: web
    name: plotter-service
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: DB_CONNECTION
        value: pgsql
      - key: OKDESK_API_TOKEN
        sync: false
      - key: OKDESK_ACCOUNT
        value: insitech
      - key: OKDESK_STATUS_CODE
        value: Equipment_transferred_repair_VSP

databases:
  - name: plotter-db
    plan: free
    databaseName: plotter
    user: plotter_user